name: Update Lift Statuses

on:
  # schedule:
    # 5分ごとに実行（UTCタイムゾーン）
    # - cron: '*/5 * * * *'
  # 手動実行も可能にする
  workflow_dispatch:

jobs:
  update-lift-statuses:
    runs-on: ubuntu-latest
    steps:
      - name: Call Update API
        run: |
          curl -X GET "https://lift-timeline.pages.dev/api/update-lift-statuses" \
          -H "Content-Type: application/json" \
          --retry 3 \
          --retry-delay 5
      
      - name: Log status
        if: always()
        run: |
          echo "API呼び出し完了: $(date)" 